name: Backoffice Main Compile, Docker build and Azure deploy

on:
  push:
    branches:
      - "main"
    
      
  workflow_dispatch:

concurrency:
  group: "main"
  cancel-in-progress: true
  

jobs:
  audodeploy-main-on-dev:
    runs-on: ubuntu-latest
    environment:
      name: "dev"

    steps:
      - name: Checkout to the Branch
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://fsttest.azurecr.io/
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fsttest.azurecr.io/fsttest/hello-world:fst
          file: ./Dockerfile
    
      - name: Deploy to Azure Dev resource group
        id: deploy-to-dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: "fst-webapp-test"
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: "fsttest.azurecr.io/fsttest/hello-world:fst"
